name: Adventure
description: Adventure Map Engins
authors: [ StarTux ]
version: 0.1-SNAPSHOT
api-version: 1.13
website: https://cavetale.com
main: com.winthier.minigames.adventure.Adventure
depend: [ SQL, Connect ]
softdepend: []
commands:
  colorfall:
    aliases: [highscore, hi, quit]
permissions: {}
