main: com.cavetale.adventure.AdventurePlugin

name: Adventure
version: 0.1-SNAPSHOT
description: Adventure Map Engins
api-version: '1.21.8'

author: StarTux
website: https://github.com/StarTux/Adventure

depend: [Core, Mytems, SQL, Creative]
softdepend: []

commands:

  adventure:
    aliases: [adv]
    description: Player command
    permission: adventure.adventure

  adventureadmin:
    aliases: [advadm]
    description: Admin command
    permission: adventure.admin

permissions:

  adventure.adventure:
    description: Use /adv
    default: op

  adventure.admin:
    description: Use /advadm
    default: op
