name: Adventure
description: Adventure Map Engins
authors: [ StarTux ]
version: 0.1-SNAPSHOT
api-version: 1.13
website: https://cavetale.com
main: com.cavetale.adventure.Adventure
depend: [Core, SQL, Creative]
softdepend: []
commands:
  adventure:
    aliases: [highscore, hi, quit]
permissions: {}
